"""emails table add

Revision ID: ea548519a279
Revises: 
Create Date: 2026-04-05 16:25:55.427278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea548519a279'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('external_thread_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_cleaned', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_message_id', name='uq_emails_external_message_id')
    )
    op.create_index('ix_emails_external_thread_id', 'emails', ['external_thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emails_external_thread_id', table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
